const Blog = require("../models/Blog");

// ---------------------------------------------------------
// CREATE BLOG
// ---------------------------------------------------------
const createBlog = async (req, res) => {
  try {
    const { title, content, authorType } = req.body;

    if (!title || !content) {
      return res.status(400).json({ message: "Title & content are required" });
    }

    const imagePath = req.file ? `/uploads/blogs/${req.file.filename}` : null;

    const blog = await Blog.create({
      title,
      content,
      authorType,
      image: imagePath,
    }); // slug auto-generated by schema

    res.status(201).json({ message: "Blog created successfully", blog });
  } catch (err) {
    console.log("Create Blog Error:", err);
    res.status(500).json({ message: "Server error while creating blog" });
  }
};

// ---------------------------------------------------------
// GET ALL BLOGS
// ---------------------------------------------------------
const getBlogs = async (req, res) => {
  try {
    const blogs = await Blog.find().sort({ createdAt: -1 });
    res.status(200).json({ blogs });
  } catch (err) {
    console.log("Get Blogs Error:", err);
    res.status(500).json({ message: "Server error fetching blogs" });
  }
};

// ---------------------------------------------------------
// GET SINGLE BLOG
// ---------------------------------------------------------
const getBlogById = async (req, res) => {
  try {
    const blog = await Blog.findById(req.params.id);

    if (!blog) return res.status(404).json({ message: "Blog not found" });

    res.status(200).json({ blog });
  } catch (err) {
    console.log("Get Blog Error:", err);
    res.status(500).json({ message: "Server error fetching blog" });
  }
};

// ---------------------------------------------------------
// UPDATE BLOG
// ---------------------------------------------------------
const updateBlog = async (req, res) => {
  try {
    const { title, content, authorType, status } = req.body;

    const existingBlog = await Blog.findById(req.params.id);
    if (!existingBlog) {
      return res.status(404).json({ message: "Blog not found" });
    }

    // If new image uploaded
    const imagePath = req.file
      ? `/uploads/blogs/${req.file.filename}`
      : existingBlog.image;

    // Only update title if changed → triggers slug update in schema
    if (title && title !== existingBlog.title) {
      existingBlog.title = title;
    }

    existingBlog.content = content || existingBlog.content;
    existingBlog.authorType = authorType || existingBlog.authorType;
    existingBlog.status = status || existingBlog.status;
    existingBlog.image = imagePath;

    await existingBlog.save(); // slug auto-updates

    res.status(200).json({
      message: "Blog updated successfully",
      blog: existingBlog,
    });
  } catch (err) {
    console.log("Update Blog Error:", err);
    res.status(500).json({ message: "Server error updating blog" });
  }
};

// ---------------------------------------------------------
// DELETE BLOG
// ---------------------------------------------------------
const deleteBlog = async (req, res) => {
  try {
    const blog = await Blog.findByIdAndDelete(req.params.id);

    if (!blog) return res.status(404).json({ message: "Blog not found" });

    res.status(200).json({ message: "Blog deleted successfully" });
  } catch (err) {
    console.log("Delete Blog Error:", err);
    res.status(500).json({ message: "Server error deleting blog" });
  }
};

// ---------------------------------------------------------
// TOTAL BLOGS
// ---------------------------------------------------------
const getTotalBlogs = async (req, res) => {
  try {
    const total = await Blog.countDocuments();
    res.status(200).json({ total });
  } catch (err) {
    console.log("Get Total Blogs Error:", err);
    res.status(500).json({ message: "Server error fetching total blogs" });
  }
};

const getBlogBySlug = async (req, res) => {
  try {
    const blog = await Blog.findOne({ slug: req.params.slug });

    if (!blog) {
      return res.status(404).json({ message: "Blog not found" });
    }

    res.status(200).json({ blog });
  } catch (err) {
    console.log("Get Blog By Slug Error:", err);
    res.status(500).json({ message: "Server error fetching blog by slug" });
  }
};

module.exports = {
  createBlog,
  getBlogs,
  getBlogById,
  updateBlog,
  deleteBlog,
  getTotalBlogs,
  getBlogBySlug,
};
